DELETE
FROM USERS;
ALTER TABLE USERS
    ALTER COLUMN USER_ID RESTART WITH 1;
DELETE
FROM FILM_GENRES;

DELETE
FROM FILMS;
ALTER TABLE FILMS
    ALTER COLUMN FILM_ID RESTART WITH 1;

DELETE
FROM MPA;
DELETE
FROM FRIEND_LIST;
DELETE
FROM GENRES;
DELETE
FROM LIKES;

CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID   INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL     VARCHAR(255) NOT NULL,
    LOGIN     VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(255) NOT NULL,
    BIRTHDAY  DATE
);

CREATE TABLE IF NOT EXISTS MPA
(
    MPA_ID   INT PRIMARY KEY,
    MPA_NAME VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS FILMS
(
    FILM_ID      INT PRIMARY KEY AUTO_INCREMENT,
    FILM_NAME    varchar(255),
    DESCRIPTION  varchar(200),
    DURATION     INT,
    RELEASE_DATE DATE,
    MPA_ID       INT REFERENCES MPA (MPA_ID)
);

CREATE TABLE IF NOT EXISTS GENRES
(
    GENRE_ID   INT PRIMARY KEY,
    GENRE_NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS FILM_GENRES
(
    PRIMARY KEY (FILM_ID, GENRE_ID),
    FILM_ID  INT REFERENCES FILMS(FILM_ID),
    GENRE_ID INT REFERENCES GENRES(GENRE_ID)
);

CREATE TABLE IF NOT EXISTS LIKES
(
    FILM_ID INT,
    USER_ID INT,
    PRIMARY KEY (FILM_ID, USER_ID),
    CONSTRAINT FK_FILM_LIKES_FILM_ID FOREIGN KEY (FILM_ID) REFERENCES FILMS (FILM_ID) ON DELETE CASCADE,
    CONSTRAINT FK_FILM_LIKES_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FRIEND_LIST
(
    USER_ID   INT NOT NULL,
    FRIEND_ID INT NOT NULL,
    PRIMARY KEY (USER_ID, FRIEND_ID),
    CONSTRAINT FK_USERS_FRIENDS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_USERS_FRIENDS_FRIEND_ID FOREIGN KEY (FRIEND_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE
);


MERGE INTO MPA(MPA_ID,MPA_NAME)
    VALUES (1,'G');
MERGE INTO MPA(MPA_ID,MPA_NAME)
    VALUES (2,'PG');
MERGE INTO MPA(MPA_ID,MPA_NAME)
    VALUES (3,'PG-13');
MERGE INTO MPA(MPA_ID,MPA_NAME)
    VALUES (4,'R');
MERGE INTO MPA(MPA_ID,MPA_NAME)
    VALUES (5,'NC-17');

MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES (1, 'Комедия');
MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES (2, 'Драма');
MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES (3, 'Мультфильм');
MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES (4, 'Фантастика');
MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES (5, 'Боевик');
MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    VALUES (6, 'Детектив');